### ISSUE TITLE
Alternative download source

### ISSUE THREAD

**Issue by IzzySoft** [gryphius/androdns#10]
Would you consider offering an alternative download source *outside* Google Play, e.g. attaching the APK to the `releases/`? Some folks cannot or do not want to use Playstore, and would love to have a place to get it from. If you'd do so, I'd offer to pick it up in [my F-Droid compatible repo](https://apt.izzysoft.de/fdroid/repo), so even automated updates would work (as long as you provide the APKs).

Of course you could also have F-Droid picking it up for the main repo (filing [an issue here](https://gitlab.com/fdroid/rfp/issues)). If your app meets the stronger requirements there, that'd be even better.

**Comment by gryphius** [comment]
Great idea - I have added the apk to the latest release at https://github.com/gryphius/androdns/releases/tag/v1.4
and will try to remember that for future releases as well. 

Feel free to pick the files up on your site. As for f-droid, there's already an open ticket ( #6 ) I personally don't have any experience with f-droid, so I'm hoping someone could offer a little help on the correct packaging, especially the external dnsjava lib

**Comment by IzzySoft** [comment]
Great, thanks! And as promised: [here it is](https://apt.izzysoft.de/fdroid/index/apk/androdns.android.leetdreams.ch.androdns). Oh, [and here](https://android.izzysoft.de/applists/category/named/network_admin_dnstools#group_369) in my app listings :wink:

Updates should automatically reach my repo within 24h of your creating of a new tag and attaching the `.apk` to it.

If you want to go for the official repo, let me know if I should help with filing the appropriate RFP (Request For Packaging). As you already wrote you'd appreciate a hand with that, let me lend mine – continuing over there then :innocent:
