### ISSUE TITLE
feature request: Support IDNA

### ISSUE THREAD

**Issue by jakopako** [gryphius/androdns#14]
At the moment it is not possible to look up records that contain non ASCII characters like for example bücher.de. It would be cool if the user would not have to enter the punycode version of the qname.

**Comment by gryphius** [comment]
fixed in 0bf3c78a37d5a4c25c220011f2b40b40b7668344

![image](https://user-images.githubusercontent.com/998308/51404094-ad48ac00-1b52-11e9-96f0-de1713a7fd22.png)
