### ISSUE TITLE
various UI improvements

### ISSUE THREAD

**Issue by gryphius** [gryphius/androdns#24]
suggested by "funny PC"

* An profile name field (at the left position of add to bookmark icon) might be more friendly if displayed in bookmark instead when present. (optional) 
( don't understand this one - needs elaboration)

* row height of bookmark entry might be taller 
-> yes, the current bookmarks / starred query UI needs improvement

* better icon color scheme(currently toolsbar icon are blank on grey, and the help info shows white text on white for me)
-> can't reproduce that one, but could use different color scheme anyway 

* one click copy for ip address in result, currently you need to drag scrollbar first and then long press to select.
-> should probably generic for all kinds of RDATA, not just IP addresses. maybe a "copy rdata" button, if the result has only one RR ?

**Comment by funnypc** [comment]
for the 1st suggestion, I mean

when bookmark 202.67.222.222:443, I could add an alias 'opendns (port 443)' so it could be showed as a friendly name in bookmark list. 
so that people who didn't know what dns is could also use this app if their friends have set bookmarks ready for them.

**Comment by gryphius** [comment]
Ah, I get it now! Yes, that is a great suggestion, I will add that

**Comment by gryphius** [comment]
> better icon color scheme(currently toolsbar icon are blank on grey, and the help info shows white text on white for me)

6d6664ce70eeed6f086a6b0c2f51f92cab71b996 replaces the png images with material design SVG images and automatically applies the system color scheme. This should now also work with Android 10 dark mode. The help text is now a dedicated activity, also with with system color scheme/dark mode support.

I have moved the other suggestions to separate tickets better keep track of them, closing this one.
